version: '3'
services: 
  xrayr: 
    image: cmdhim/xrayr:0.7.0
    container_name: HIM
    volumes:
      - ./config.yml:/etc/XrayR/config.yml # 映射配置文件夹
      - ./dns.json:/etc/XrayR/dns.json 
      - ./cert:/etc/XrayR/cert
      - ./geoip.dat:/etc/XrayR/geoip.dat
      - ./geosite.dat:/etc/XrayR/geosite.dat
    restart: always
    network_mode: host
